pyg-team/pytorch-frame

README.md
docs/source/get_started/handle_text.rst

fix missing import and device transfer

Fix README example

---

docs/source/get_started/handle_text.rst
docs/source/modules/transforms.rst
torch_frame/data/dataset.py
torch_frame/gbdt/tuned_catboost.py
torch_frame/gbdt/tuned_xgboost.py
torch_frame/nn/conv/tab_transformer_conv.py
torch_frame/nn/conv/table_conv.py
torch_frame/nn/conv/trompt_conv.py
torch_frame/nn/decoder/decoder.py
torch_frame/nn/encoder/encoder.py
torch_frame/nn/encoder/stype_encoder.py
torch_frame/nn/models/excelformer.py
torch_frame/nn/models/ft_transformer.py
torch_frame/nn/models/resnet.py
torch_frame/nn/models/tab_transformer.py
torch_frame/nn/models/tabnet.py
torch_frame/nn/models/trompt.py
torch_frame/transforms/base_transform.py
torch_frame/transforms/cat_to_num_transform.py
torch_frame/transforms/fittable_base_transform.py
torch_frame/transforms/mutual_information_sort.py
torch_frame/utils/io.py

Also fix `ft_transformer_text.py` link

Fix formatting of documentation

---

test/data/test_multi_nested_tensor.py
torch_frame/data/multi_nested_tensor.py

Add more tests and docs for `MultiNestedTensor`

---

CHANGELOG.md
test/datasets/test_fake_dataset.py
test/test_stype.py
torch_frame/__init__.py
torch_frame/config/__init__.py
torch_frame/config/text_tokenizer.py
torch_frame/data/dataset.py
torch_frame/data/mapper.py
torch_frame/data/multi_nested_tensor.py
torch_frame/data/stats.py
torch_frame/data/tensor_frame.py
torch_frame/datasets/fake.py
torch_frame/stype.py
torch_frame/testing/text_embedder.py
torch_frame/testing/text_tokenizer.py
torch_frame/typing.py

Add basic text tokenized functionalities. Encoder change to be in the following PR.

Add basic text tokenized

---

CHANGELOG.md
test/data/test_multi_nested_tensor.py
torch_frame/data/dataset.py
torch_frame/data/multi_nested_tensor.py

Add concat dim=0 for `MultiNestedTensor`
Next PRs
- Column slicing
- Column concat

Supports advanced indexing of MultiNestedTensor (part 2)

---

CHANGELOG.md
test/data/test_multi_nested_tensor.py
torch_frame/data/multi_nested_tensor.py

Column slicing and indexing + some clean-up

Support advanced indexing of MultiNestedTensor (part 3)

---

CHANGELOG.md
test/data/test_dataset.py
test/data/test_mapper.py
test/test_stype.py
torch_frame/__init__.py
torch_frame/data/dataset.py
torch_frame/data/mapper.py
torch_frame/data/stats.py
torch_frame/stype.py

Sequence stype is very similar to multi_categorical stype, so I might as well add it.

Add Numerical Sequence Stype

---

CHANGELOG.md
test/data/test_multi_nested_tensor.py
torch_frame/data/multi_nested_tensor.py

Support concatenating `MultiNestedTensor` along `dim=1`

Support column concatenation of `MultiNestedTensor`

---

CHANGELOG.md
test/data/test_stats.py
torch_frame/data/stats.py

hello--please advise if this function should return a different format/value if this case arises

handle if ser is all nan

---

test/transforms/cat_to_num_transform.py
torch_frame/datasets/fake.py
torch_frame/transforms/cat_to_num_transform.py

Handle the case where target contains nans in CatToNumTransform

---

test/nn/models/test_compile.py
torch_frame/nn/models/excelformer.py
torch_frame/nn/models/tab_transformer.py
torch_frame/nn/models/tabnet.py
torch_frame/nn/models/trompt.py

add default NAStrategy to models

---

test/datasets/test_titanic.py
torch_frame/data/dataset.py

In place sort should be `xxx.sort()`

Fix column names in place sort

---

test/datasets/test_data_frame_benchmark.py
torch_frame/datasets/data_frame_benchmark.py
torch_frame/datasets/dota2.py
torch_frame/datasets/kdd_census_income.py
torch_frame/datasets/tabular_benchmark.py
torch_frame/gbdt/gbdt.py
torch_frame/nn/base.py
torch_frame/nn/conv/excelformer_conv.py
torch_frame/nn/conv/table_conv.py
torch_frame/nn/models/excelformer.py
torch_frame/nn/models/resnet.py
torch_frame/nn/models/tab_transformer.py
torch_frame/nn/models/tabnet.py
torch_frame/nn/models/trompt.py
torch_frame/transforms/cat_to_num_transform.py
torch_frame/transforms/fittable_base_transform.py
torch_frame/transforms/mutual_information_sort.py
torch_frame/utils/concat.py
torch_frame/utils/io.py

Fix typo and docs

---

CHANGELOG.md
pyproject.toml
torch_frame/datasets/multimodal_text_benchmark.py

- Add `multi-categorical` to `MultimodalTextBenchmark`
- Add `pyarrow` to the dependencies as need it to read parquet for `MultimodalTextBenchmark`

Add `multi-categorical` to `MultimodalTextBenchmark`

---

examples/transformers_text.py

- Update transformers text example performance for some datasets
- Fix bug for saving file when there is `/` in the model name

Update transformers text example

---

CHANGELOG.md
test/test_stype.py
test/utils/test_infer_stype.py
torch_frame/datasets/fake.py
torch_frame/stype.py
torch_frame/utils/__init__.py
torch_frame/utils/infer_stype.py

https://github.com/pyg-team/pytorch-frame/issues/215

Auto-inference of `stype`

---

CHANGELOG.md
benchmark/data_frame_benchmark.py
examples/tuned_gbdt.py
test/gbdt/test_gbdt.py
torch_frame/__init__.py
torch_frame/gbdt/gbdt.py
torch_frame/gbdt/tuned_catboost.py
torch_frame/gbdt/tuned_xgboost.py
torch_frame/typing.py

so that we can use different `eval_metric` and `loss`, e.g., use MAE for regression instead of the default RMSE for regression, or use Accuracy for binary classification instead of the default ROC-AUC.
Also did some refactoring to clean-up the code.

Support `Metric` in `GBDT` + clean-up

---

test/data/test_multi_nested_tensor.py
torch_frame/data/multi_nested_tensor.py

See title.
No need for a changelog entry as `MultiNestedTensor` hasn't been released yet.

Respect device in `MultiNestedTensor.from_tensor_mat`

---

CHANGELOG.md
test/conftest.py
test/data/test_tensor_frame.py
test/utils/test_io.py
torch_frame/data/tensor_frame.py
torch_frame/stype.py
torch_frame/utils/concat.py
torch_frame/utils/io.py

Towards column-wise encoder: https://github.com/pyg-team/pytorch-frame/issues/232
Also fixed `concat`, `save`, `load` utils for `MultiEmbeddingTensor`.

Add `get_col_feat` to `TensorFrame`

---

CHANGELOG.md
torch_frame/datasets/multimodal_text_benchmark.py

Added time columns to the `MultimodalTextBenchmark`

Added time columns to the `MultimodalTextBenchmark`

---

CHANGELOG.md
benchmark/README.md
benchmark/data_frame_benchmark.py
pyproject.toml
test/gbdt/test_gbdt.py
torch_frame/gbdt/__init__.py
torch_frame/gbdt/tuned_lightgbm.py

From https://github.com/pyg-team/pytorch-frame/issues/245
- Binary Classification + Small + 0
```
Best is trial 17 with value: 0.9283801711103639.
{'args': {'task_type': 'binary_classification', 'scale': 'small', 'idx': 0, 'epochs': 50, 'num_trials': 20, 'num_repeats': 5, 'model_type': 'LightGBM', 'seed': 0, 'result_path': './output/results.pt'}, 'best_val_metric': 0.9283801711103639, 'best_test_metric': 0.9314460189332364, 'best_cfg': {'verbosity': -1, 'bagging_freq': 1, 'max_depth': 8, 'learning_rate': 0.009535731905301808, 'num_leaves': 428, 'subsample': 0.7982234374896812, 'colsample_bytree': 0.4258609181729451, 'reg_alpha': 0.19993496122846377, 'reg_lambda': 0.0117270935126881, 'min_child_samples': 64, 'min_data_in_leaf': 64, 'objective': 'binary', 'metric': 'auc'}, 'total_time': …
```

Add `LightGBM`

---

torch_frame/data/multi_embedding_tensor.py
torch_frame/data/multi_nested_tensor.py
torch_frame/data/multi_tensor.py

Addresses https://github.com/pyg-team/pytorch-frame/pull/217#discussion_r1397971207. Closes #235.

Refactor multi tensor indexing

---

.github/workflows/linting.yml
pyproject.toml

Addresses https://github.com/pyg-team/pytorch-frame/pull/279#discussion_r1419025436.

Update mypy GHA

---

examples/transformers_text.py
torch_frame/data/stats.py
torch_frame/datasets/multimodal_text_benchmark.py

Makes sure all multimodal datasets work with `transformer_text.py`

fix issues in text benchmark dataset

---

README.md
docs/source/handling_advanced_stypes/handle_heterogeneous_stypes.rst

Minor updates for README and docs

README and docs minor update

---

CHANGELOG.md
pyproject.toml
torch_frame/__init__.py

will be in after https://github.com/pyg-team/pytorch-frame/pull/291 is in.

v0.2.0 release

---

docs/source/handling_advanced_stypes/handle_text.rst

Address https://github.com/pyg-team/pytorch-frame/pull/302

Clarify the use of both `text_embedded` and `text_tokenized`

---

docs/source/handling_advanced_stypes/handle_text.rst

Makes the tutorial more step-by-step.

Further polish text tutorial

---

README.md

simplify readme. remove the expansion.

Minor `README` update

---

CHANGELOG.md
test/nn/models/test_trompt.py
torch_frame/nn/models/excelformer.py
torch_frame/nn/models/ft_transformer.py
torch_frame/nn/models/resnet.py
torch_frame/nn/models/tab_transformer.py
torch_frame/nn/models/tabnet.py
torch_frame/nn/models/trompt.py

- Add `stype_encoder_dict` to some models
- Fixes #315
- Also fixes some docs

Add `stype_encoder_dict` to some models

---

pyproject.toml
torch_frame/data/multi_tensor.py
torch_frame/utils/concat.py
torch_frame/utils/infer_stype.py
torch_frame/utils/io.py

Add type annotations to `torch_frame.utils.*`

---

docs/source/handling_advanced_stypes/handle_heterogeneous_stypes.rst

fix typo in `handle heterogeneous stypes` docs
Thank you for creating a cool and fun package.

typo in docs. 

---

docs/source/handling_advanced_stypes/handle_text.rst
examples/transformers_text.py

for better readability of the example code and tutorial.

Improve comments of `attention_mask` padding

---

CHANGELOG.md
test/data/test_multi_embedding_tensor.py
test/data/test_multi_nested_tensor.py
torch_frame/data/multi_tensor.py

Added support for Boolean masks in `_MultiTensor` class based on issue https://github.com/pyg-team/pytorch-frame/issues/331

support Boolean masks in _MultiTensor

---

examples/tab_transformer.py

ROC AUC should not take argmax value

Fix `tab_transformer.py` evaluation bug

---

torch_frame/utils/infer_stype.py

Suppress the annoying warnings while inferring stypes via trial and error.

Suppress UserWarning in `infer_stype`

---

CHANGELOG.md
benchmark/data_frame_text_benchmark.py

Add dataframe text benchmark script

Add dataframe text benchmark script

---

CHANGELOG.md
test/datasets/test_data_frame_text_benchmark.py
torch_frame/datasets/data_frame_text_benchmark.py
torch_frame/utils/infer_stype.py
torch_frame/utils/split.py

Make sure text benchmark datasets (from `MultimodalTextBenchmark`) split same with https://arxiv.org/abs/2111.02705

Text benchmark dataset split

---

torch_frame/datasets/amphibians.py

For https://github.com/pyg-team/pytorch-frame/issues/350

[Multilabel classification] Introduce a real world multilabel classification dataset

---

README.md

Adjust README image size to a proper one

Fix README image size

---

README.md

Add PyTorch Frame paper link to readme

Add PyTorch Frame paper link to readme

---

torch_frame/datasets/fake.py

Fix https://github.com/pyg-team/pytorch-frame/pull/391#discussion_r1576038650

Make sure binary classification `FakeDataset` has both pos/neg labels

---

test/transforms/test_cat_to_num_transform.py
torch_frame/transforms/cat_to_num_transform.py

Fixes https://github.com/pyg-team/pytorch-frame/issues/388

Better error message for `CatToNumTransform`

---

examples/llm_embedding.py

fix embedding script

---

torch_frame/nn/models/excelformer.py

Fix ExcelFormer Example Link

---

.github/workflows/prev_testing.yml
.github/workflows/testing.yml

- Update testing torch version

Update testing torch version

---

CHANGELOG.md
torch_frame/nn/encoder/stype_encoder.py

Don't create the same tensor every iteration in N/A handling

---

benchmark/README.md

No need for a changelog entry as this change impacts no users.

Add benchmark results for large-scale multiclass classification task

---

.github/workflows/documentation.yml
.github/workflows/linting.yml
.github/workflows/testing.yml

To save our limited number of runners for other PRs or repos :)

CI: Add concurrency to workflows triggered on PRs

---

test/data/test_multi_nested_tensor.py
torch_frame/data/multi_tensor.py

Support 0-dim tensors in tensor slicing
