pyg-team/pytorch-frame

CHANGELOG.md
test/data/test_multi_nested_tensor.py
torch_frame/data/__init__.py
torch_frame/data/multi_nested_tensor.py
torch_frame/nn/models/tabnet.py

* Add basic functionality of `MultiNestedTensor` that supports Pytorch Tensor of shape `(num_rows, num_cols, *)`, where the last dimension can have varying sizes.
Basic usage is that
```python
multi_nested_tensor = MultiNestedTensor.from_tensor_mat(tensor_mat)
multi_nested_tensor[i, j]
multi_nested_tensor[i]
multi_nested_tensor[[3, 4, 5]]
```
Column index select, row slicing/arange will be supported in later PR.

Add `MultiNestedTensor`

---

test/data/test_mapper.py
torch_frame/data/mapper.py

I got the following error when processing a customer's data
```
File "/home/ubuntu/git/pytorch-frame/examples/example.py", line 93, in <module>
dataset.materialize()
File "/home/ubuntu/git/pytorch-frame/torch_frame/data/dataset.py", line 332, in materialize
self._tensor_frame = self._to_tensor_frame_converter(self.df, device)
File "/home/ubuntu/git/pytorch-frame/torch_frame/data/dataset.py", line 135, in __call__
out = self._get_mapper(col).forward(df[col], device=device)
File "/home/ubuntu/git/pytorch-frame/torch_frame/data/mapper.py", line 130, in forward
emb = self.text_embedder(ser_list[i:i + self.batch_size])
File "/home/ubuntu/git/pytorch-frame/examples/example.py", line 83, in __call__
embeddings = self.model.encode(sentences, convert_to_numpy=False,
File …
```

convert series type to string before putting it into text embedder

---

CHANGELOG.md
test/data/test_dataset.py
test/data/test_mapper.py
torch_frame/__init__.py
torch_frame/data/dataset.py
torch_frame/data/mapper.py
torch_frame/data/stats.py
torch_frame/datasets/fake.py
torch_frame/stype.py
torch_frame/typing.py

Based on the comments in #128 , the following changes are made in this pr:
1. Added an `MULTI_COUNT` stat type for `multicategorical` stype.
2. Modified the name of `multi_categorical` stype to `multicategorical` stype.
3. Modified the mappings. Now missing values will be mapped to `-1`, no value is considered as a category and unseen values are all ignored.

Fix multicategorical stype based on review comments

---

test/data/test_multi_nested_tensor.py
torch_frame/data/multi_nested_tensor.py

as `MultiNestedTensor` should be used as read-only. Also setting values will be slow and not preferred.

Disallow `__setitem__` for `MultiNestedTensor`

---

test/data/test_stats.py
torch_frame/data/stats.py

Fixes https://github.com/pyg-team/pytorch-frame/issues/195

Fix stats computation for `sequence_numerical` with `NaN` elements

---

pyproject.toml

I've just realised that we were installing https://pypi.org/project/torch-frame/ as one of our dependencies.
Please check and uninstall it from your dev environment:
```bash
pip uninstall torch-frame
```

Update dev dependency

---

CHANGELOG.md
test/data/test_multi_embedding_tensor.py
torch_frame/data/multi_embedding_tensor.py
torch_frame/data/multi_nested_tensor.py
torch_frame/data/multi_tensor.py

Part of #88.
```python
import torch
from torch_frame.data import MultiEmbeddingTensor
tensor_list = [
torch.tensor([[0, 1, 2], [6, 7, 8]]),  # col1
torch.tensor([[3, 4], [9, 10]]),       # col2
torch.tensor([[5], [11]]),             # col3
]
met = MultiEmbeddingTensor.from_tensor_list(tensor_list)
print(met)
print(met[0])
print(met[0].values)
print(met[0].offset)
```

Support `int` index in `MultiEmbeddingTensor`

---

examples/llm_embedding.py
examples/transformers_text.py

Fixes https://github.com/pyg-team/pytorch-frame/issues/154 by using different paths for caching different tensor frame objects.

Config specific `path` during dataset materialization

---

CHANGELOG.md
examples/trompt.py
test/nn/models/test_compile.py
test/nn/models/test_trompt.py
torch_frame/nn/models/trompt.py

so that the behavior of all tensor frame models is aligned.
Instead we add `forward_stacked` that outputs stacked embeddings for layer-wise loss computation.

Make `Trompt` output 2d embeddings in `forward`.

---

torch_frame/nn/models/resnet.py

Current test passed because we always have target column and `len(col_stats) - 1` happens to be the same as the target column. This no longer holds when we need to handle a table with no target column. This PR fixes the issue by computing the number of columns based on `col_names_dict`.

Fix `ResNet`'s `in_channels` calculations

---

CHANGELOG.md
docs/source/get_started/handle_text.rst
docs/source/get_started/modular_design.rst
examples/llm_embedding.py
examples/mercari.py
examples/transformers_text.py
test/nn/encoder/test_stype_encoder.py
test/nn/encoder/test_stypewise_encoder.py
torch_frame/data/dataset.py
torch_frame/data/stats.py
torch_frame/nn/encoder/stype_encoder.py

Based on suggestion https://github.com/pyg-team/pytorch-frame/issues/206#issuecomment-1811525804
A lot of diff is due to the new formatter: charliermarsh.ruff

Automatic inference of `in_channels` in `LinearEmbeddingEncoder` for `stype.text_embedding`

---

examples/transformers_text.py

Fuse tokenizer and text encoder to avoid unnecessary errors such as tokenizer is not align with the text encoder

Text example fuse tokenizer and encoder to a single class

---

test/data/test_multi_embedding_tensor.py
torch_frame/data/multi_embedding_tensor.py

Fixes a bug in `[:, int]` indexing in `MultiEmbeddingTensor` caught by this new test case:
```python
assert_equal(
tensor_list,
MultiEmbeddingTensor.cat(
[met[:, i] for i in range(met.size(1))],
dim=1,
),
)
```
Addresses https://github.com/pyg-team/pytorch-frame/pull/193#discussion_r1387650926 (cc @weihua916)
Addresses https://github.com/pyg-team/pytorch-frame/pull/181#discussion_r1383949234 (cc @yiweny)
---
No changelog entry needed as the feature hasn't been released yet.

Fix `[:, int]` indexing in `MultiEmbeddingTensor`

---

CHANGELOG.md
test/data/test_stats.py
test/nn/encoder/test_stype_encoder.py
test/nn/encoder/test_stypewise_encoder.py
torch_frame/data/stats.py
torch_frame/nn/encoder/__init__.py
torch_frame/nn/encoder/stype_encoder.py

We can migrate `stype_encoder` of `text_embedded` into `LinearMultiEmbeddingEncoder`.
Then, we can rename `LinearMultiEmbeddingEncoder` into `LinearEmbeddingEncoder`, so that both `embedding` and `text_embedded` stypes use `LinearEmbeddingEncoder`.

Add `LinearMultiEmbeddingEncoder` for `embedding` stype

---

CHANGELOG.md
test/nn/encoder/test_stype_encoder.py
torch_frame/nn/encoder/stype_encoder.py
torch_frame/nn/encoder/stypewise_encoder.py

so that `StypeEncoder` can use the information of `col_names` when necessary. Useful for per-column text model for `text_tokenized`.

Add optional `col_names` argument in `StypeEncoder`

---

examples/excelformer.py
examples/llm_embedding.py
examples/mercari.py
examples/revisiting.py
examples/tab_transformer.py
examples/tabnet.py
examples/transformers_text.py
examples/trompt.py
examples/tuned_gbdt.py
test/nn/models/test_compile.py

This PR adds `--compile` option to examples.
I ran all of these examples with the default args. Some (e.g. `tabnet.py`) run faster while others run slower than eager, e.g., due to excessive recompilations.
Although most examples run without any error raised, there're two examples we need to investigate further for `torch.compile` support in the future:
1. `mercari.py` fails due to numerical accuracy issue (similarly to https://github.com/pytorch/pytorch/issues/114109)
```bash
$ python examples/mercari.py --compile
Traceback (most recent call last):
File "/home/akihiro/work/github.com/pyg-team/pytorch-frame/examples/mercari.py", line 69, in <module>
dataset.materialize(path=osp.join(path, "data.pt"))
File "/home/akihiro/work/github.com/pyg-team/pytorch-frame/torch_frame/data/dataset.py", …
```

Add `--compile` option to examples

---

CHANGELOG.md
docs/source/get_started/handle_text.rst
docs/source/get_started/introduction.rst
docs/source/get_started/modular_design.rst

Hi everyone!
I was reading through the introduction tutorial of the library and could spot minor typos. I decided to try and fix some of them.
At the same time, I updated the internal links to classes and methods when I could.
Here is the list of modifications proposed in this commit:
- Correcting minor typos.
- Updating internal links when the path is no longer correct (e.g. `torch_frame.TensorFrame` -> `torch_frame.data.TensorFrame`).
- Including the 's' for plural links into the pastil using a trick described in https://stackoverflow.com/questions/19403972/writing-terms-in-plural-without-the-redundancy (e.g. :class:`torch.Tensor`\ s -> :class:`Tensors<torch.Tensor>`).
- Providing links for existing classes previously unlinked (e.g. :obj:`Dataset` -> :obj:`torch_frame.data.Dataset`).
I …

[Documentation] Typos & link fix

---

CHANGELOG.md
examples/transformers_text.py
test/datasets/test_fake_dataset.py
test/nn/encoder/test_stype_encoder.py
test/nn/encoder/test_stypewise_encoder.py
test/utils/test_io.py
torch_frame/data/dataset.py
torch_frame/datasets/amazon_fine_food_reviews.py
torch_frame/datasets/fake.py
torch_frame/datasets/multimodal_text_benchmark.py

Renamed `text_tokenized_cfg` into `col_to_text_tokenized_cfg`

Renamed `text_tokenized_cfg` into `col_to_text_tokenized_cfg`

---

.pre-commit-config.yaml
pyproject.toml

I'm in favor of adding mypy (or any other type checker) so that I don't have to guess how to correctly annotate PyF. Also, we no longer need to comment things like https://github.com/pyg-team/pytorch-frame/pull/258/files#r1412843422 as mypy will raise errors :)
Run
```
pip install mypy
mypy  # automatically reads config in pyproject.toml
```
or via pre-commit
```
pip install pre-commit
pre-commit install
```

Add `mypy` as a type checker

---

.github/workflows/linting.yml
.pre-commit-config.yaml

pre-commit.ci doesn't support having data more than 250MiB as seen in [this run](https://results.pre-commit.ci/run/github/677240069/1701948936.LN0QYu8HRtCf3o7UpKs6bQ):
```
Build of https://github.com/pre-commit/mirrors-mypy:torch==2.1.1@v1.7.1 for python@python3 exceeds tier max size 250MiB: 4.5GiB
```
This PR moves mypy from pre-commit.ci to GHA to unblock #276 and future PRs for type check in CI.

Drop mypy from pre-commit.ci and run mypy in a GHA workflow

---

test/data/test_dataset.py
test/data/test_stats.py
torch_frame/data/dataset.py
torch_frame/data/mapper.py
torch_frame/data/stats.py
torch_frame/datasets/fake.py

- Remove redundancy, increase code sharing.
- Explicitly let `sep=None` handle `list` cell in multicategorical columns
- More type checking of canonicalized `col_to_pattern` to raise informative errors.

Clean up `col_to_pattern` logic

---

test/gbdt/test_gbdt.py
torch_frame/gbdt/tuned_catboost.py
torch_frame/gbdt/tuned_lightgbm.py
torch_frame/gbdt/tuned_xgboost.py

- At BP stage, we should not force users to supply `y` in TensorFrame.
- Also cache input to avoid redundant computation from tensor frame in every objective call.

Allow `y=None` in `predict()` of `GBDT`

---

test/data/test_dataset.py
torch_frame/data/dataset.py

so that we can transform `DataFrame` without a target column at BP/test stage.

Make `target_column` optional in `DataFrameToTensorFrameConverter`

---

examples/mercari.py
examples/transformers_text.py

- Fixes #293
- Fixes `transformers_text.py` in Python 3.9 or before
IMO, this PR doesn't require a changelog entry.

Fix examples

---

docs/source/handling_advanced_stypes/handle_text.rst
test/nn/encoder/test_stypewise_encoder.py
torch_frame/data/tensor_frame.py

Next step (after `v0.2.0` release): Avoid unnecessary `clone()` in stype encoder and still pass this test. Ref: https://github.com/pyg-team/pytorch-frame/issues/254

Verify no in-place modification in `StypeEncoder`

---

CHANGELOG.md
torch_frame/nn/encoder/stype_encoder.py

Fix `TimestampEncoder` not using `CyclicEncoding` for cyclic features

---

torch_frame/nn/conv/excelformer_conv.py

I guess norm_2 was not being used in ExcelFormer.

missing norm_2 in excel_former

---

torch_frame/data/tensor_frame.py

This pr removes the extra {} in TensorFrame docs.

Fix typo in `TensorFrame` docs

---

torch_frame/data/dataset.py

If we don't do a `copy` here. Users might change `col_to_stype` after declaring the `Dataset` class and before calling `dataset.materialize()`. This will cause an error because user might add new keys to `col_to_stype`.
Example code snippet that hit this issue:
```
text_encoder = TextToEmbedding(model="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
device=device)
col_to_stype={'Surname': text_embedded, 'CreditScore':numerical,
'Geography': categorical, 'Age': numerical,
'Tenure': numerical, 'Balance': numerical, 
'NumOfProducts': numerical,'HasCrCard': categorical,
'IsActiveMember': categorical,'EstimatedSalary': numerical}
test_dataset = Dataset(df=pd.read_csv('/kaggle/input/playground-series-s4e1/test.csv'),
col_to_stype=col_to_stype, …
```

Better User Experience: fix reference issue in Dataset

---

.gitignore
CHANGELOG.md
test/data/test_tensor_frame.py
torch_frame/data/tensor_frame.py

This PR adds support for empty `TensorFrame` similarly to `pandas.DataFrame`.

Support empty `TensorFrame({}, {})`

---

torch_frame/_stype.py
torch_frame/data/tensor_frame.py

```diff
>>> import torch_frame
>>> torch_frame.numerical, str(torch_frame.numerical), f"{torch_frame.numerical}"
- (<stype.numerical: 'numerical'>, 'stype.numerical', 'stype.numerical')
+ (<stype.numerical: 'numerical'>, 'numerical', 'numerical')
```

Allow `str` as a key of `TensorFrame`

---

benchmark/data_frame_text_benchmark.py

Two different classes called `TaskType` were imported, shadowing each other.

Avoid shadowing task type in text benchmark

---

pyproject.toml

To avoid bug related to the recent `mpmath` version upgrade.
```
FAILED test/nn/models/test_compile.py::test_compile_graph_break[FTTransformer] - AttributeError: module 'mpmath' has no attribute 'rational'
FAILED test/nn/models/test_compile.py::test_compile_graph_break[ResNet] - AttributeError: module 'mpmath' has no attribute 'rational'
FAILED test/nn/models/test_compile.py::test_compile_graph_break[TabNet] - AttributeError: module 'mpmath' has no attribute 'rational'
FAILED test/nn/models/test_compile.py::test_compile_graph_break[TabTransformer] - AttributeError: module 'mpmath' has no attribute 'rational'
FAILED test/nn/models/test_compile.py::test_compile_graph_break[Trompt] - AttributeError: module 'mpmath' has no attribute 'rational'
FAILED …
```

Fix `mpmath` version

---

CHANGELOG.md
benchmark/encoder/README.md
benchmark/encoder/encoder_benchmark.py

Preliminary benchmarks of [RelBench](https://github.com/snap-stanford/relbench/blob/main/examples/gnn.py) showed that a lot of execution time is spent on encoders. This PR introduces encoders benchmarking suite that can server as a tool for performance inspection.

Add benchmarking suite for encoders

---

CHANGELOG.md
torch_frame/nn/encoder/stype_encoder.py

This PR introduces small improvements that resulted in an average 1.5x speedup in `na_forward` execution time.
`get_na_mask` is a heavy operation, whose result may be cached at the pre-condition checking step.
Additionally, when we deal with 2D `feat`, we can use `torch.where` to efficiently fill `NaN`s across all columns.

Improve performance of Encoder's `na_forward` method

---

CHANGELOG.md
torch_frame/nn/models/resnet.py

Fix `FCResidualBlock` by removing relu

---

test/nn/models/test_trompt.py

`stype_encoder_dicts` needs to be initialized inside `test_trompt()`. otherwise, it will be persisted across different parametrization, causing an unexpected error.

Fix `test_trompt.py`

---

pyproject.toml

Add `torchmetrics` to `pyproject.py` full dependencies
As we need to use it in the benchmark

Add `torchmetrics` to `pyproject.py` full dependencies

---

benchmark/data_frame_text_benchmark.py

Labels in the text benchmarks are imbalanced and weighting the positive labels improves performance.
Experiments done on `fake` dataset (5% positive labels)  with `text_embedded` and `RoBERTa` encodings:
- `ResNet` result changes 91.1% -> 93.4% 
- `FTTransformer` result remains unchanged
- `Trompt` result changes 95.2% -> 95.8%
The differences were even more stark with distilled roberta, but we aren't reporting those anywhere so I didn't note them down.
More results are pending

Handle label imbalance in binary classification tasks on text benchmark

---

test/nn/models/test_mlp.py
torch_frame/nn/models/mlp.py
torch_frame/nn/models/resnet.py

Fix https://github.com/pyg-team/pytorch-frame/pull/372#discussion_r1518735977

Fix `MLP` normalization argument

---

benchmark/data_frame_text_benchmark.py

Allow multiple times retry to get OpenAI embeddings if some requests failed

Add retry to get OpenAI embeddings

---

benchmark/data_frame_text_benchmark.py

Make `DataFrameTextBenchmark` script `pos_weight` optional as some datasets may not need this (such as `kick`)

Make `DataFrameTextBenchmark` script `pos_weight` optional

---

torch_frame/datasets/data_frame_benchmark.py
torch_frame/datasets/data_frame_text_benchmark.py
torch_frame/datasets/multimodal_text_benchmark.py

Fix text dataset stats and benchmark dataset materialize return

Fix text dataset stats and benchmark materialize return

---

CHANGELOG.md
torch_frame/gbdt/gbdt.py
torch_frame/typing.py

This PR adds the $R^2$ metric (coefficient of determination) for regression tasks.
This is a popular metric and has some desirable properties:
1. normalized to range (-inf, 1]
2. global mean baseline gets score 0
3. intuitive interpretation as the proportion of variance explained

Add R2 metric

---

torch_frame/data/mapper.py

The following FutureWarning is fixed:
```
test/data/test_mapper.py::test_categorical_tensor_mapper
/usr/local/lib/python3.10/dist-packages/torch_frame/data/mapper.py:113: FutureWarning: Series.__getitem__ 
treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels 
(consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
ser = pd.Series(self.categories[index].index)
```

[FutureWarn] Fix FutureWarning in `CategoricalTensorMapper`.

---

torch_frame/testing/decorators.py

I've noticed that the tests with the `withPackage` test decorators
```
@withPackage("torch>=2.1.0")
def test_some_test(...):
. . .
```
are not being executed, even though I have `torch=2.4.0` installed on my machine.
```
nn/models/test_compile.py::test_compile_graph_break[FTTransformer] SKIPPED (Package(s) {'torch>=2.1.0'} are not installed)
```
To be precise, I am using Torch version `2.4.0a0+f70bd71a48.nv24.06` which has an unexpected version ID format for the  for `pytorch-frame` .
The proposed PR uses standard [Python version handling](https://packaging.python.org/en/latest/specifications/version-specifiers/), which covers the `dev` case previously treated separately.

Fixing Bug in Version Handling.

---

test/transforms/test_cat_to_num_transform.py

The following UserWarnings are fixed:
```
test/transforms/test_cat_to_num_transform.py::test_cat_to_num_transform_on_categorical_only_dataset[True]
test/transforms/test_cat_to_num_transform.py::test_cat_to_num_transform_on_categorical_only_dataset[False]
/opt/pyg/pytorch-frame/test/transforms/test_cat_to_num_transform.py:55: UserWarning: To copy construct from a tensor, 
it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather 
than torch.tensor(sourceTensor).
assert torch.allclose(
test/transforms/test_cat_to_num_transform.py::test_cat_to_num_transform_with_loading[TaskType.REGRESSION]
test/transforms/test_cat_to_num_transform.py::test_cat_to_num_transform_with_loading[TaskType.BINARY_CLASSIFICATION] …
```

[UserWarning] Fixing UserWarnings in two tests.

---

test/gbdt/test_gbdt.py
torch_frame/gbdt/tuned_xgboost.py

support xgboost early stopping

---

CHANGELOG.md
torch_frame/nn/encoder/stype_encoder.py

`start_idx` and `end_idx` used at `feat.values[:, start_idx:end_idx]` are on device, which leads to cuda synchronizations.

Remove CUDA synchronizations by slicing input tensor with `int` instead of CUDA tensors in `nn.LinearEmbeddingEncoder`

---

CHANGELOG.md
torch_frame/nn/encoder/stype_encoder.py

I understand the intention of the assertion introduced in #307, however, we should not check it at runtime as it causes a D2H sync. It should rather be covered in tests, and I believe there's no need to add new tests as existing test cases already cover the correctness of the N/A imputation.

Don't put assertions on N/A imputation correctness

---

torch_frame/gbdt/tuned_xgboost.py

```
_______ test_gbdt_with_save_load[task_type_and_metric4-stypes1-XGBoost] ________
gbdt_cls = <class 'torch_frame.gbdt.tuned_xgboost.XGBoost'>
stypes = [<stype.categorical: 'categorical'>]
task_type_and_metric = (<TaskType.MULTICLASS_CLASSIFICATION: 'multiclass_classification'>, <Metric.ACCURACY: 'accuracy'>)
@pytest.mark.parametrize('gbdt_cls', [
CatBoost,
XGBoost,
LightGBM,
])
@pytest.mark.parametrize('stypes', [
[stype.numerical],
[stype.categorical],
[stype.text_embedded],
[stype.numerical, stype.numerical, stype.text_embedded],
])
@pytest.mark.parametrize('task_type_and_metric', [
(TaskType.REGRESSION, Metric.RMSE),
(TaskType.REGRESSION, Metric.MAE),
(TaskType.BINARY_CLASSIFICATION, Metric.ACCURACY),
(TaskType.BINARY_CLASSIFICATION, Metric.ROCAUC), …
```

fix error in xgboost

---

CHANGELOG.md
test/transforms/test_cat_to_num_transform.py
torch_frame/transforms/cat_to_num_transform.py

Fixes this:
```console
$ python benchmark/data_frame_benchmark.py --scale large --idx 1 --model ExcelFormer --task_type multiclass_classification
Downloading https://archive.ics.uci.edu/static/public/158/poker+hand.zip
Traceback (most recent call last):
File "<console>", line 1, in <module>
File "/home/aki/work/github.com/pyg-team/pytorch-frame/torch_frame/transforms/fittable_base_transform.py", line 25, in __call__
return self.forward(copy.copy(tf))
File "/home/aki/work/github.com/pyg-team/pytorch-frame/torch_frame/transforms/fittable_base_transform.py", line 88, in forward
transformed_tf = self._forward(tf)
File "/home/aki/work/github.com/pyg-team/pytorch-frame/torch_frame/transforms/cat_to_num_transform.py", line 133, in _forward
(num_classes - 1)] = ((v + target_mean) /
RuntimeError: …
```

Fix size mismatch error when `CatToNumTransform` sees only a subset of labels at test time

---

test/utils/test_io.py
torch_frame/__init__.py
torch_frame/utils/io.py

Does the same as https://github.com/pyg-team/pytorch_geometric/pull/9618/. No need for a changelog as the `weights_only=True` change in #423 hasn't been released yet.

Fail `torch.load(weights=True)` gracefully

---

CHANGELOG.md
torch_frame/nn/encoder/stype_encoder.py

This PR fixes an issue in the `LinearEmbeddingEncoder` class. The forward function does not increment the `start_idx` variable, so only the first one is used correctly if multiple embedding columns are present.
This probably affects the results in the [RelBench](https://arxiv.org/pdf/2407.20060) paper, so I suggest double-checking those.

Fix offset in LinearEmbeddingEncoder

---

torch_frame/gbdt/tuned_lightgbm.py

Using `categorical_feature` parameter in `lightgbm.Dataset()` instead of `lightgbm.train(...)` eliminates the following warnings:
```
test/gbdt/test_gbdt.py: 60 warnings
/usr/local/lib/python3.10/dist-packages/lightgbm/engine.py:187: LGBMDeprecationWarning: Argument 'categorical_feature' 
to train() is deprecated and will be removed in a future release. Set 'categorical_feature' when calling lightgbm.Dataset() 
instead. See https://github.com/microsoft/LightGBM/issues/6435.
_emit_dataset_kwarg_warning("train", "categorical_feature")
```

Removing the deprecated `categorical_feature` parameter from `lightgbm.train(...)` function calls.

---

test/nn/models/test_compile.py

Tighten assert condition in graph break tests

---

.github/actions/setup/action.yml
.github/workflows/linting.yml
.pre-commit-config.yaml
CHANGELOG.md
README.md
benchmark/data_frame_benchmark.py
benchmark/encoder/encoder_benchmark.py
docs/requirements.txt
docs/source/get_started/installation.rst
examples/llm_embedding.py
examples/tutorial.py
pyproject.toml
readthedocs.yml
test/data/test_multi_embedding_tensor.py
test/data/test_multi_nested_tensor.py
test/nn/test_simple_basecls.py
torch_frame/data/mapper.py
torch_frame/data/multi_embedding_tensor.py
torch_frame/data/multi_nested_tensor.py
torch_frame/data/multi_tensor.py
torch_frame/nn/encoder/encoder.py
torch_frame/typing.py
torch_frame/utils/concat.py

Drop support for Python 3.8

---

.github/CONTRIBUTING.md
README.md
docs/source/get_started/installation.rst
pyproject.toml

This PR makes a cosmetic change and makes no change that affects users.
`-` and `_` mean the same thing at pypi.org/project/pytorch-frame as per https://packaging.python.org/en/latest/specifications/name-normalization/#name-normalization.

Consistent PyPI name `pytorch-frame`

---

test/data/test_tensor_frame.py
torch_frame/data/tensor_frame.py

```python
import torch
import torch_frame
from torch_frame.data import TensorFrame
feat_dict = {torch_frame.categorical: torch.randint(0, 3, size=(10, 1))}
col_names_dict = {torch_frame.categorical: 'cat_1'}
TensorFrame(feat_dict, col_names_dict)
```
```
Traceback (most recent call last):
File "/home/aki/work/github.com/kumo-ai/kumo/../../akihironitta/gist/test.py", line 7, in <module>
TensorFrame(feat_dict, col_names_dict)
File "/home/aki/miniconda3/envs/kumo/lib/python3.10/site-packages/torch_frame/data/tensor_frame.py", line 78, in __init__
self.validate()
File "/home/aki/miniconda3/envs/kumo/lib/python3.10/site-packages/torch_frame/data/tensor_frame.py", line 113, in validate
raise ValueError(
ValueError: The expected number of columns for categorical feature is 5, which does not …
```

Raise a friendly message when a `str` is provided to `TensorFrame(col_names_dict)` instead of a `list[str]`

---

CHANGELOG.md
benchmark/data_frame_benchmark.py
benchmark/data_frame_text_benchmark.py
examples/trompt.py
examples/trompt_multi_gpu.py
test/nn/models/test_compile.py
test/nn/models/test_trompt.py
torch_frame/nn/models/trompt.py

Adds an example for training a model on multiple GPUs.
```console
$ python examples/trompt_multi_gpu.py
```
To enable it, this PR modifies `Trompt` accordingly:
```diff
- out = Trompt(...).forward_stacked(tf)  # forward_stacked is removed
+ out = Trompt(...)(tf)
assert out.size() == (batch_size, num_layers, num_channels)
```
* Unlike `examples/trompt.py`, it computes training accuracy batch-wise instead of computing it at the end of each epoch to save time (although model parameters change over steps within each epoch).
* It reduces losses and metrics with `all_reduce` and `torchmetrics`'s API across all ranks at the end of each epoch.
* It avoids unnecessary device synchronisations within each epoch, e.g., by not calling `float(cuda_tensor)`, and by setting `repeat_interleave(..., …

Add an example of training a tabular model on multiple GPUs

---

examples/trompt.py
torch_frame/nn/conv/trompt_conv.py

Reduces training time by 29% by:
* removing unnecessary stream and D2H synchronisations
* replacing `einsum` with `matmul`
* making data copied async wrt host
* using TF32 for matmuls
Benchmarked the change using `jannis` dataset on `g6.4xlarge` that has a L4 GPU. To reproduce, run:
```console
$ python examples/trompt.py --dataset jannis
$ python examples/trompt.py --dataset jannis --compile
```
Average time per training step:
| | master (`A`) | **this PR** (`B`) | `B/A` |
|:-:|:-:|:-:|:-:|
|eager|742.79 ms|**741.22** ms|0.99x|
|compile|262.24 ms|**186.80** ms|0.71x|
Average time per evaluation step:
| | master (`A`) | **this PR** (`B`) | `B/A` |
|:-:|:-:|:-:|:-:|
|eager|303.76 ms|**302.73** ms|1.00x|
|compile|58.75 ms|**56.27** ms|0.96x|
---
Happy holidays! 🎄🧹

Optimize the `Trompt` example to reduce training time by ~30%

---

readthedocs.yml

https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/

Fix documentation build

---

.pre-commit-config.yaml
CHANGELOG.md
pyproject.toml

since Ruff is already introduce it would simplify and speed-up linting

lint: switch `pyupgrade` to Ruff's rule UP

---

.github/actions/setup/action.yml

Fixes:
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
```

Fix NumPy and PyTorch incompatibility error in CI

---

.github/actions/setup/action.yml
test/gbdt/test_gbdt.py

https://github.com/catboost/catboost/releases/tag/v1.2.8 started supporting Python 3.13 via https://github.com/catboost/catboost/issues/2748.

Support CatBoost in Python 3.13

---

torch_frame/utils/infer_stype.py

The `logger.warn()` method is deprecated since Python2.7 and replaced with `logger.warning()`. It leads to those warnings:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```

Migrate to modern logger interface
